spring:
  application:
    name: order
  jpa:
    hibernate:
      ddl-auto: none
  datasource:
    driver-class-name: org.postgresql.Driver
    url: ${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5432/orders}
    username: db_owner
    password: test

kafka:
  server: ${KAFKA_SERVER:localhost:9092}
  groupId: orders

server:
  servlet:
    context-path: /order-service/
  port: 8080